export const categoryKeywords: { [key: string]: string[] } = {
  World: [
    "war",
    "global",
    "foreign",
    "abroad",
    "ceasefire",
    "ukraine",
    "russia",
    "israel",
    "gaza",
    "conflict",
    "diplomacy",
    "NATO",
    "crisis",
    "sanctions",
    "military",
    "refugees",
    "peace talks",
  ],
  Politics: [
    "election",
    "government",
    "policy",
    "politics",
    "senate",
    "congress",
    "Biden",
    "Trump",
    "Labour",
    "minister",
    "parliament",
    "legislation",
    "campaign",
    "White House",
    "Prime Minister",
    "scandal",
    "impeachment",
    "democracy",
    "referendum",
    "diplomat",
    "election",
    "president",
  ],
  Business: [
    "business",
    "economy",
    "market",
    "stocks",
    "startup",
    "trade",
    "funding",
    "IPO",
    "acquisition",
    "merger",
    "revenue",
    "profit",
    "loss",
    "investment",
    "inflation",
    "recession",
    "financial",
    "bank",
    "currency",
    "employment",
  ],
  Technology: [
    "technology",
    "tech",
    "gadgets",
    "software",
    "cyber",
    "internet",
    "innovation",
    "digital",
    "robotics",
    "blockchain",
    "cryptocurrency",
    "hacking",
    "coding",
    "social media",
    "startup",
    "big tech",
    "cloud",
    "quantum",
    "data",
    "privacy",
    "space",
    "biotech",
    "fintech",
    "google",
    "facebook",
    "netflix",
    "amazon",
    "apple",
  ],
  Sports: [
    "sports",
    "game",
    "match",
    "tournament",
    "league",
    "rugby",
    "football",
    "soccer",
    "basketball",
    "cricket",
    "Olympics",
    "athlete",
    "tennis",
    "golf",
    "swimming",
    "marathon",
    "championship",
    "world cup",
    "race",
    "team",
    "medal",
  ],
  Health: [
    "health",
    "medicine",
    "doctor",
    "hospital",
    "covid",
    "pandemic",
    "disease",
    "vaccine",
    "virus",
    "mental health",
    "surgery",
    "pharmaceutical",
    "treatment",
    "nutrition",
    "fitness",
    "epidemic",
    "public health",
    "medical research",
    "outbreak",
    "healthcare",
    "drug",
  ],
  Entertainment: [
    "entertainment",
    "movie",
    "film",
    "celebrity",
    "music",
    "concert",
    "theater",
    "series",
    "show",
    "Hollywood",
    "award",
    "festival",
    "actor",
    "actress",
    "director",
    "producer",
    "streaming",
    "cinema",
    "pop culture",
    "album",
    "song",
  ],
  Science: [
    "science",
    "research",
    "discovery",
    "experiment",
    "NASA",
    "quantum",
    "space",
    "climate",
    "physics",
    "biology",
    "chemistry",
    "innovation",
    "technology",
    "astronomy",
    "genetics",
    "ecology",
    "environment",
    "scientific study",
    "lab",
    "earth",
    "planet",
    "universe",
    "theory",
    "scientist",
  ],
  Environment: [
    "environment",
    "climate",
    "green",
    "sustainability",
    "wildlife",
    "global warming",
    "pollution",
    "renewable",
    "biodiversity",
    "conservation",
    "recycling",
    "carbon",
    "emissions",
    "deforestation",
    "natural disaster",
    "earthquake",
    "flood",
    "drought",
    "hurricane",
    "ecosystem",
    "ozone",
    "endangered species",
    "solar",
    "wind energy",
  ],
  US: [
    "America",
    "U.S",
    "Trump",
    "Biden",
    "senate",
    "congress",
    "White House",
    "Supreme Court",
    "governor",
    "New York",
    "California",
    "Washington",
    "Texas",
    "Florida",
    "state",
    "federal",
    "midterms",
    "constitution",
    "Republican",
    "Democrat",
  ],
  Other: [
    "miscellaneous",
    "variety",
    "general",
    "unspecified",
    "undefined",
    "various",
    "random",
  ],
};
